from __future__ import annotations

from dataclasses import dataclass, asdict, field
from typing import List, Literal, Optional

from src.layer3.schemas_b import VideoAssessment

RecommendationCategory = Literal["narration", "recording", "moderation"]


@dataclass
class Recommendation:
    """
    One coaching recommendation generated by Step 6.2.

    Current MVP assumptions:
    - input comes only from 5.1-B
    - output is session-level
    - no timestamped evidence yet
    - no 5.1-A friction evidence yet
    """
    category: RecommendationCategory
    title: str
    summary: str
    advice: List[str]

    trigger_field: str
    trigger_value: str

    priority: int
    evidence_note: Optional[str] = None
    tags: List[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return asdict(self)


class RecommendationEngine:
    """
    Step 6.2 Coaching Recommendation Engine (MVP)

    Input:
        - one VideoAssessment from 5.1-B

    Output:
        - zero or more high-level coaching recommendations
        - grouped into narration / recording / moderation

    Design notes:
        - narration templates are driven by narration_quality
        - recording templates are driven by recording_quality
        - moderation templates are driven by coaching_evidence
        - this version is intentionally template-based
    """

    def generate(self, assessment: VideoAssessment) -> List[Recommendation]:
        """
        Generate recommendations from one 5.1-B assessment object.
        """
        recommendations: List[Recommendation] = []

        narration_rec = self._build_narration_recommendation(assessment)
        if narration_rec is not None:
            recommendations.append(narration_rec)

        recording_rec = self._build_recording_recommendation(assessment)
        if recording_rec is not None:
            recommendations.append(recording_rec)

        moderation_rec = self._build_moderation_recommendation(assessment)
        if moderation_rec is not None:
            recommendations.append(moderation_rec)

        return sorted(recommendations, key=lambda item: item.priority, reverse=True)

    # ------------------------------------------------------------------
    # Narration templates
    # ------------------------------------------------------------------

    def _build_narration_recommendation(
        self,
        assessment: VideoAssessment,
    ) -> Optional[Recommendation]:
        value = assessment.narration_quality

        if value == "rich":
            return None

        if value == "adequate":
            return Recommendation(
                category="narration",
                title="Narration could be more consistently explicit",
                summary=(
                    "The participant provided enough verbal content for analysis, "
                    "but the session would benefit from more regular think-aloud narration."
                ),
                advice=[
                    "Encourage the participant to briefly explain what they are noticing while moving through the task.",
                    "Prefer short, regular verbal updates instead of only commenting after an action is completed.",
                    "Use neutral prompts to invite process narration when long silent stretches appear.",
                ],
                trigger_field="narration_quality",
                trigger_value=value,
                priority=1,
                evidence_note="5.1-B marks narration as adequate but not rich.",
                tags=["narration", "template", "session-level"],
            )

        if value == "sparse":
            return Recommendation(
                category="narration",
                title="Increase participant verbalisation",
                summary=(
                    "The session contains only fragments or very short utterances, "
                    "which limits the usefulness of downstream interpretation."
                ),
                advice=[
                    "Encourage more continuous think-aloud narration throughout the task.",
                    "Use neutral moderator prompts such as asking what the participant is seeing or trying to do.",
                    "Aim for brief but frequent verbal check-ins rather than long periods of silence.",
                ],
                trigger_field="narration_quality",
                trigger_value=value,
                priority=3,
                evidence_note="5.1-B marks narration as sparse at the session level.",
                tags=["narration", "coverage", "session-level"],
            )

        if value == "none":
            return Recommendation(
                category="narration",
                title="Narration is insufficient for reliable interpretation",
                summary=(
                    "The participant barely spoke during the session, making it difficult "
                    "to interpret intent, confusion, or decision-making."
                ),
                advice=[
                    "Set think-aloud expectations clearly before the task begins.",
                    "Use neutral reminders to encourage verbalisation without directing task behaviour.",
                    "Treat detailed behavioural conclusions from this session with caution if low narration persists.",
                ],
                trigger_field="narration_quality",
                trigger_value=value,
                priority=4,
                evidence_note="5.1-B marks narration as effectively absent.",
                tags=["narration", "analysis-risk", "session-level"],
            )

        return None

    # ------------------------------------------------------------------
    # Recording templates
    # ------------------------------------------------------------------

    def _build_recording_recommendation(
        self,
        assessment: VideoAssessment,
    ) -> Optional[Recommendation]:
        value = assessment.recording_quality

        if value == "good":
            return None

        if value == "acceptable":
            return Recommendation(
                category="recording",
                title="Recording quality is usable but should be improved",
                summary=(
                    "The session is still usable for analysis, but defects in the recording "
                    "may reduce confidence in detailed interpretation."
                ),
                advice=[
                    "Check microphone clarity and ambient noise before starting future sessions.",
                    "Reduce clipping, brief audio gaps, or interruptions where possible.",
                    "Mark this session as usable with caution if fine-grained analysis is required.",
                ],
                trigger_field="recording_quality",
                trigger_value=value,
                priority=2,
                evidence_note="5.1-B marks recording quality as acceptable rather than good.",
                tags=["recording", "quality", "session-level"],
            )

        if value == "poor":
            return Recommendation(
                category="recording",
                title="Recording quality limits reliable downstream analysis",
                summary=(
                    "The session recording is broken, incomplete, or substantially degraded, "
                    "which weakens the reliability of interpretation."
                ),
                advice=[
                    "Treat this session as low-confidence evidence.",
                    "Improve recording setup and audio checks before the next session begins.",
                    "Consider excluding this session from analyses that require detailed behavioural evidence.",
                ],
                trigger_field="recording_quality",
                trigger_value=value,
                priority=5,
                evidence_note="5.1-B marks the session as barely usable for analysis.",
                tags=["recording", "reliability", "analysis-risk"],
            )

        return None

    # ------------------------------------------------------------------
    # Moderation templates
    # ------------------------------------------------------------------

    def _build_moderation_recommendation(
        self,
        assessment: VideoAssessment,
    ) -> Optional[Recommendation]:
        value = assessment.coaching_evidence

        if value == "none":
            return None

        if value == "explicit":
            return Recommendation(
                category="moderation",
                title="Reduce directive moderator coaching",
                summary=(
                    "The moderator appears to have directly guided the participant, "
                    "which may reduce the naturalness and validity of the observed behaviour."
                ),
                advice=[
                    "Avoid telling the participant exactly where to click or what the answer is.",
                    "Prefer neutral prompts that encourage the participant to explain their own thinking.",
                    "Interpret task success with caution when explicit moderator coaching is present.",
                ],
                trigger_field="coaching_evidence",
                trigger_value=value,
                priority=4,
                evidence_note="5.1-B marks moderator coaching as explicit at the session level.",
                tags=["moderation", "coaching-evidence", "session-validity"],
            )

        return None


def render_recommendations(recommendations: List[Recommendation]) -> str:
    """
    Helper for local debugging / CLI preview.
    """
    if not recommendations:
        return "No recommendations generated."

    lines: List[str] = []
    for idx, item in enumerate(recommendations, start=1):
        lines.append(f"{idx}. [{item.category}] {item.title}")
        lines.append(f"   trigger: {item.trigger_field}={item.trigger_value}")
        lines.append(f"   priority: {item.priority}")
        lines.append(f"   summary: {item.summary}")
        if item.evidence_note:
            lines.append(f"   note: {item.evidence_note}")
        for advice_idx, advice_line in enumerate(item.advice, start=1):
            lines.append(f"   - advice {advice_idx}: {advice_line}")
        lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    """
    Minimal smoke test for local development.

    Run from project root:
        python -m src.coaching.recommendation_engine
    """
    example = VideoAssessment(
        narration_quality="sparse",
        recording_quality="acceptable",
        coaching_evidence="explicit",
    )

    engine = RecommendationEngine()
    output = engine.generate(example)

    print("=== RAW OUTPUT ===")
    for item in output:
        print(item.to_dict())

    print("\n=== HUMAN READABLE ===")
    print(render_recommendations(output))