from __future__ import annotations

from dataclasses import dataclass, asdict, field
from collections import Counter
from typing import Any, List, Literal, Optional

from src.layer3.schemas_b import VideoAssessment

RecommendationCategory = Literal[
    "narration",
    "recording",
    "moderation",
    "severity",
    "friction-aggregation",
    "meta",
]

_SEVERITY_RANK = {
    "S1": 1,
    "S2": 2,
    "S3": 3,
    "S4": 4,
    "S5": 5,
    "S6": 6,
}

# Short, demo-friendly labels for F1-F7. Used by the friction-aggregation
# builder to render evidence_note text without leaking the canonical
# definitions document. Keep in sync with docs/l3_design.md §Friction Types.
_FRICTION_LABELS = {
    "F1": "Comprehension",
    "F2": "Confidence",
    "F3": "Accessibility",
    "F4": "Unresponsive",
    "F5": "Unexpected",
    "F6": "Not Found",
    "F7": "Excessive Effort",
}

# Severity rungs that count as "non-trivial" for the friction-aggregation
# trigger. A multi-pattern report that consists entirely of S5/S6 findings
# is downgraded — surfacing a high-priority aggregation item there would
# misrepresent low-impact noise as a structural pattern.
_NON_TRIVIAL_SEVERITIES = {"S1", "S2", "S3", "S4"}

# Meta-coaching triggers (5.1-B narration + recording combination).
_META_NARRATION_TRIGGER = {"none", "sparse"}
_META_RECORDING_TRIGGER = {"poor", "acceptable"}

@dataclass
class Recommendation:
    """
    One coaching recommendation generated by Step 6.2.

    Current MVP assumptions:
    - input comes only from 5.1-B
    - output is session-level
    - no timestamped evidence yet
    - no 5.1-A friction evidence yet
    """
    category: RecommendationCategory
    title: str
    summary: str
    advice: List[str]

    trigger_field: str
    trigger_value: str

    priority: int
    evidence_note: Optional[str] = None
    tags: List[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return asdict(self)


class RecommendationEngine:
    """
    Step 6.2 Coaching Recommendation Engine (MVP)

    Input:
        - one VideoAssessment from 5.1-B

    Output:
        - zero or more high-level coaching recommendations
        - grouped into narration / recording / moderation

    Design notes:
        - narration templates are driven by narration_quality
        - recording templates are driven by recording_quality
        - moderation templates are driven by coaching_evidence
        - this version is intentionally template-based
    """

    def generate(
        self,
        assessment: VideoAssessment,
        findings: Optional[List[dict[str, Any]]] = None,
    ) -> List[Recommendation]:
        """
        Generate recommendations from one 5.1-B assessment object.

        Optional:
            findings: 5.1-A finding-level records used for severity-aware
            coaching. This keeps the original session-level MVP behaviour
            backward-compatible while enabling the Step 6.2 V2 extension.
        """
        findings = findings or []
        recommendations: List[Recommendation] = []

        # Session-level builders (5.1-B). Build all three first so we can
        # decide whether the meta builder should suppress narration + recording.
        narration_rec = self._build_narration_recommendation(assessment)
        recording_rec = self._build_recording_recommendation(assessment)
        moderation_rec = self._build_moderation_recommendation(assessment)
        meta_rec = self._build_meta_recommendation(assessment)

        if meta_rec is not None:
            # Suppress isolated narration + recording in favour of one
            # combined meta item; moderation is independent and still emits.
            recommendations.append(meta_rec)
        else:
            if narration_rec is not None:
                recommendations.append(narration_rec)
            if recording_rec is not None:
                recommendations.append(recording_rec)

        if moderation_rec is not None:
            recommendations.append(moderation_rec)

        # Finding-level builders (5.1-A) — independent of meta suppression.
        severity_rec = self._build_severity_recommendation(findings)
        if severity_rec is not None:
            recommendations.append(severity_rec)

        friction_rec = self._build_friction_aggregation_recommendation(findings)
        if friction_rec is not None:
            recommendations.append(friction_rec)

        return sorted(recommendations, key=lambda item: item.priority, reverse=True)

    # ------------------------------------------------------------------
    # Finding-level severity templates
    # ------------------------------------------------------------------

    def _build_severity_recommendation(
        self,
        findings: List[dict[str, Any]],
    ) -> Optional[Recommendation]:
        """
        Optional 5.1-A extension.

        Uses finding-level severity_s to generate one severity-aware coaching
        recommendation. This extension summarises the severity distribution,
        selects the highest severity, and emits one aggregated coaching item
        rather than one item per finding.
        """
        severity_values = [
            str(item.get("severity_s"))
            for item in findings
            if item.get("severity_s") in _SEVERITY_RANK
        ]

        if not severity_values:
            return None

        counts = Counter(severity_values)
        highest = min(severity_values, key=lambda value: _SEVERITY_RANK[value])
        total = sum(counts.values())

        severity_summary = ", ".join(
            f"{key}={counts[key]}"
            for key in ["S1", "S2", "S3", "S4", "S5", "S6"]
            if counts.get(key)
        )

        top_findings = self._select_top_findings(findings, limit=3)
        evidence_examples = [
            str(item.get("finding"))
            for item in top_findings
            if item.get("finding")
        ]

        evidence_note = f"5.1-A severity distribution: {severity_summary}."
        if evidence_examples:
            evidence_note += " Representative findings: " + " | ".join(evidence_examples)

        if highest in {"S1", "S2"}:
            return Recommendation(
                category="severity",
                title="Prioritise task-blocking friction before general coaching",
                summary=(
                    f"The session contains {total} finding-level issue(s), including "
                    f"task-blocking or near-blocking severity ({highest})."
                ),
                advice=[
                    "Review the highest-severity findings before applying general coaching templates.",
                    "Prioritise issues that prevented or substantially disrupted task completion.",
                    "Use the highest-severity findings to guide focused follow-up coaching.",
                ],
                trigger_field="severity_s",
                trigger_value=highest,
                priority=5,
                evidence_note=evidence_note,
                tags=["severity", "finding-level", "high-priority"],
            )

        if highest in {"S3", "S4"}:
            return Recommendation(
                category="severity",
                title="Review high-friction moments before lower-level issues",
                summary=(
                    f"The session contains {total} finding-level issue(s), with the "
                    f"highest severity at {highest}."
                ),
                advice=[
                    "Identify the common pattern behind the higher-severity findings.",
                    "Focus coaching on the most disruptive parts of the session first.",
                    "Avoid treating all findings as equal when severity levels differ.",
                ],
                trigger_field="severity_s",
                trigger_value=highest,
                priority=4,
                evidence_note=evidence_note,
                tags=["severity", "finding-level", "targeted-coaching"],
            )

        if total >= 5:
            return Recommendation(
                category="severity",
                title="Monitor repeated low-severity friction patterns",
                summary=(
                    f"The session contains {total} low-severity finding-level issues. "
                    "Individually they are minor, but repetition may still indicate a pattern."
                ),
                advice=[
                    "Review whether repeated low-severity findings point to the same underlying issue.",
                    "Combine minor findings into one coaching theme rather than treating each separately.",
                    "Use this as a lower-priority follow-up after higher-severity issues are addressed.",
                ],
                trigger_field="severity_s",
                trigger_value="S5/S6",
                priority=2,
                evidence_note=evidence_note,
                tags=["severity", "finding-level", "low-priority"],
            )

        return None

    def _select_top_findings(
        self,
        findings: List[dict[str, Any]],
        limit: int = 3,
    ) -> List[dict[str, Any]]:
        """
        Select representative findings ordered by severity.
        """
        valid = [
            item
            for item in findings
            if item.get("severity_s") in _SEVERITY_RANK
        ]

        return sorted(
            valid,
            key=lambda item: _SEVERITY_RANK[str(item.get("severity_s"))],
        )[:limit]

    # ------------------------------------------------------------------
    # Finding-level friction-aggregation template
    # ------------------------------------------------------------------

    def _build_friction_aggregation_recommendation(
        self,
        findings: List[dict[str, Any]],
    ) -> Optional[Recommendation]:
        """
        Optional 5.1-A extension.

        Emit one aggregated coaching item when a session shows multi-pattern
        friction across several friction types — issuing one parallel
        recommendation per friction type would duplicate coaching effort.

        Trigger guard rails (per cc.md / codex.md convergence):

        - `total_findings >= 5` (avoid surfacing aggregation on tiny samples)
        - `>= 3 distinct friction types` among findings
        - at least one finding sits in {S1,S2,S3,S4} — a session of pure
          S5/S6 noise should not be elevated to a multi-pattern coaching
          item.
        """
        # Filter rows with valid friction_type AND severity_s; we need both
        # to apply the non-trivial-severity guard rail without crashing on
        # NaN / None / unknown enum values.
        valid = [
            item
            for item in findings
            if item.get("friction_type") in _FRICTION_LABELS
            and item.get("severity_s") in _SEVERITY_RANK
        ]
        if len(valid) < 5:
            return None

        friction_counts = Counter(
            str(item["friction_type"]) for item in valid
        )
        distinct_types = len(friction_counts)
        if distinct_types < 3:
            return None

        if not any(
            item.get("severity_s") in _NON_TRIVIAL_SEVERITIES
            for item in valid
        ):
            return None

        # Stable order: by count desc, then by F-code asc for ties.
        ordered_types = [
            ft for ft, _ in sorted(
                friction_counts.items(),
                key=lambda kv: (-kv[1], kv[0]),
            )
        ]
        trigger_value = ",".join(ordered_types)
        dominant = ordered_types[0]
        secondary = ordered_types[1:3]  # at most two for the advice copy

        type_summary = ", ".join(
            f"{ft}={friction_counts[ft]}" for ft in ordered_types
        )

        evidence_note = (
            f"5.1-A: total={len(valid)} findings across {distinct_types} "
            f"distinct friction types ({type_summary})."
        )

        secondary_text = (
            ", ".join(
                f"{code} {_FRICTION_LABELS[code]}" for code in secondary
            )
            if secondary
            else "the remaining friction types"
        )

        return Recommendation(
            category="friction-aggregation",
            title=(
                f"Multi-pattern friction across {distinct_types} categories — "
                f"anchor coaching on the dominant pattern"
            ),
            summary=(
                f"This session shows {len(valid)} findings spanning "
                f"{distinct_types} distinct friction types "
                f"({trigger_value}). Coaching should follow the dominant "
                f"pattern first rather than issuing one item per type."
            ),
            advice=[
                (
                    f"Treat {dominant} ({_FRICTION_LABELS[dominant]}) as the "
                    f"primary coaching anchor; secondary types ({secondary_text}) "
                    f"provide supporting context."
                ),
                (
                    "Review the highest-severity findings within the dominant "
                    "pattern before broadening to other types."
                ),
                (
                    "Avoid issuing parallel recommendations for each friction "
                    "type when patterns interact within the same session."
                ),
            ],
            trigger_field="friction_type_distribution",
            trigger_value=trigger_value,
            priority=4,
            evidence_note=evidence_note,
            tags=[
                "friction-aggregation",
                "finding-level",
                "multi-pattern",
            ],
        )

    # ------------------------------------------------------------------
    # Session-level meta template
    # ------------------------------------------------------------------

    def _build_meta_recommendation(
        self,
        assessment: VideoAssessment,
    ) -> Optional[Recommendation]:
        """
        Optional 5.1-B extension.

        When narration quality is low *and* recording quality is at the same
        time degraded, emitting two parallel recommendations (one per
        category) creates noise: weak audio also weakens the narration
        signal, so coaching the participant on think-aloud cadence before
        fixing the recording channel is unlikely to land.

        This builder emits one meta item that names the combined situation,
        and `generate()` suppresses the isolated narration + recording items
        when this meta item fires. Moderation, severity, and friction-
        aggregation are not affected.
        """
        narration = assessment.narration_quality
        recording = assessment.recording_quality

        if narration not in _META_NARRATION_TRIGGER:
            return None
        if recording not in _META_RECORDING_TRIGGER:
            return None

        return Recommendation(
            category="meta",
            title="Address recording setup before deepening narration coaching",
            summary=(
                f"Both narration ({narration}) and recording ({recording}) "
                f"are below ideal. Improving the recording channel first "
                f"will let later narration coaching land more reliably; "
                f"isolated narration and recording recommendations are "
                f"suppressed in favour of this combined item."
            ),
            advice=[
                (
                    "Resolve recording-setup issues — microphone clarity, "
                    "ambient noise, clipping — before pushing for richer "
                    "narration."
                ),
                (
                    "Re-state think-aloud expectations to the participant "
                    "only after the recording channel is reliable, so "
                    "verbalisation is captured cleanly."
                ),
                (
                    "Treat current narration-quality readings as lower-"
                    "confidence until recording stabilises."
                ),
            ],
            trigger_field="narration_recording_combo",
            trigger_value=f"{narration}+{recording}",
            priority=6,
            evidence_note=(
                f"5.1-B narration={narration} ∧ recording={recording}; "
                "isolated narration / recording recommendations are "
                "suppressed in favour of this meta item."
            ),
            tags=["meta", "session-level", "suppression"],
        )

    # ------------------------------------------------------------------
    # Narration templates
    # ------------------------------------------------------------------

    def _build_narration_recommendation(
        self,
        assessment: VideoAssessment,
    ) -> Optional[Recommendation]:
        value = assessment.narration_quality

        if value == "rich":
            return None

        if value == "adequate":
            return Recommendation(
                category="narration",
                title="Narration could be more consistently explicit",
                summary=(
                    "The participant provided enough verbal content for analysis, "
                    "but the session would benefit from more regular think-aloud narration."
                ),
                advice=[
                    "Encourage the participant to briefly explain what they are noticing while moving through the task.",
                    "Prefer short, regular verbal updates instead of only commenting after an action is completed.",
                    "Use neutral prompts to invite process narration when long silent stretches appear.",
                ],
                trigger_field="narration_quality",
                trigger_value=value,
                priority=1,
                evidence_note="5.1-B marks narration as adequate but not rich.",
                tags=["narration", "template", "session-level"],
            )

        if value == "sparse":
            return Recommendation(
                category="narration",
                title="Increase participant verbalisation",
                summary=(
                    "The session contains only fragments or very short utterances, "
                    "which limits the usefulness of downstream interpretation."
                ),
                advice=[
                    "Encourage more continuous think-aloud narration throughout the task.",
                    "Use neutral moderator prompts such as asking what the participant is seeing or trying to do.",
                    "Aim for brief but frequent verbal check-ins rather than long periods of silence.",
                ],
                trigger_field="narration_quality",
                trigger_value=value,
                priority=3,
                evidence_note="5.1-B marks narration as sparse at the session level.",
                tags=["narration", "coverage", "session-level"],
            )

        if value == "none":
            return Recommendation(
                category="narration",
                title="Narration is insufficient for reliable interpretation",
                summary=(
                    "The participant barely spoke during the session, making it difficult "
                    "to interpret intent, confusion, or decision-making."
                ),
                advice=[
                    "Set think-aloud expectations clearly before the task begins.",
                    "Use neutral reminders to encourage verbalisation without directing task behaviour.",
                    "Treat detailed behavioural conclusions from this session with caution if low narration persists.",
                ],
                trigger_field="narration_quality",
                trigger_value=value,
                priority=4,
                evidence_note="5.1-B marks narration as effectively absent.",
                tags=["narration", "analysis-risk", "session-level"],
            )

        return None

    # ------------------------------------------------------------------
    # Recording templates
    # ------------------------------------------------------------------

    def _build_recording_recommendation(
        self,
        assessment: VideoAssessment,
    ) -> Optional[Recommendation]:
        value = assessment.recording_quality

        if value == "good":
            return None

        if value == "acceptable":
            return Recommendation(
                category="recording",
                title="Recording quality is usable but should be improved",
                summary=(
                    "The session is still usable for analysis, but defects in the recording "
                    "may reduce confidence in detailed interpretation."
                ),
                advice=[
                    "Check microphone clarity and ambient noise before starting future sessions.",
                    "Reduce clipping, brief audio gaps, or interruptions where possible.",
                    "Mark this session as usable with caution if fine-grained analysis is required.",
                ],
                trigger_field="recording_quality",
                trigger_value=value,
                priority=2,
                evidence_note="5.1-B marks recording quality as acceptable rather than good.",
                tags=["recording", "quality", "session-level"],
            )

        if value == "poor":
            return Recommendation(
                category="recording",
                title="Recording quality limits reliable downstream analysis",
                summary=(
                    "The session recording is broken, incomplete, or substantially degraded, "
                    "which weakens the reliability of interpretation."
                ),
                advice=[
                    "Treat this session as low-confidence evidence.",
                    "Improve recording setup and audio checks before the next session begins.",
                    "Consider excluding this session from analyses that require detailed behavioural evidence.",
                ],
                trigger_field="recording_quality",
                trigger_value=value,
                priority=5,
                evidence_note="5.1-B marks the session as barely usable for analysis.",
                tags=["recording", "reliability", "analysis-risk"],
            )

        return None

    # ------------------------------------------------------------------
    # Moderation templates
    # ------------------------------------------------------------------

    def _build_moderation_recommendation(
        self,
        assessment: VideoAssessment,
    ) -> Optional[Recommendation]:
        value = assessment.coaching_evidence

        if value == "none":
            return None

        if value == "explicit":
            return Recommendation(
                category="moderation",
                title="Reduce directive moderator coaching",
                summary=(
                    "The moderator appears to have directly guided the participant, "
                    "which may reduce the naturalness and validity of the observed behaviour."
                ),
                advice=[
                    "Avoid telling the participant exactly where to click or what the answer is.",
                    "Prefer neutral prompts that encourage the participant to explain their own thinking.",
                    "Interpret task success with caution when explicit moderator coaching is present.",
                ],
                trigger_field="coaching_evidence",
                trigger_value=value,
                priority=4,
                evidence_note="5.1-B marks moderator coaching as explicit at the session level.",
                tags=["moderation", "coaching-evidence", "session-validity"],
            )

        return None


def render_recommendations(recommendations: List[Recommendation]) -> str:
    """
    Helper for local debugging / CLI preview.
    """
    if not recommendations:
        return "No recommendations generated."

    lines: List[str] = []
    for idx, item in enumerate(recommendations, start=1):
        lines.append(f"{idx}. [{item.category}] {item.title}")
        lines.append(f"   trigger: {item.trigger_field}={item.trigger_value}")
        lines.append(f"   priority: {item.priority}")
        lines.append(f"   summary: {item.summary}")
        if item.evidence_note:
            lines.append(f"   note: {item.evidence_note}")
        for advice_idx, advice_line in enumerate(item.advice, start=1):
            lines.append(f"   - advice {advice_idx}: {advice_line}")
        lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    """
    Minimal smoke test for local development.

    Run from project root:
        python -m src.coaching.recommendation_engine
    """
    example = VideoAssessment(
        narration_quality="sparse",
        recording_quality="acceptable",
        coaching_evidence="explicit",
    )

    engine = RecommendationEngine()
    output = engine.generate(
        example,
        findings=[
            {
                "finding": "Participant could not locate the required pathway and needed help.",
                "friction_type": "F6",
                "severity_s": "S2",
                "rationale": "The task could not be completed independently.",
            },
            {
                "finding": "Participant hesitated before recovering from a confusing label.",
                "friction_type": "F2",
                "severity_s": "S5",
                "rationale": "The issue was recoverable but still visible.",
            },
        ],
    )

    print("=== RAW OUTPUT ===")
    for item in output:
        print(item.to_dict())

    print("\n=== HUMAN READABLE ===")
    print(render_recommendations(output))
